name: Deploy to GitHub Pages
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  check-replays:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile --ignore-scripts

      - run: pnpm exec nuxt prepare

      - run: pnpm exec tsx ci/existsReplay.ts

  check-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch origin ${{ github.base_ref }} --depth=1

      - name: Warn if ReleaseNotes.ts is unchanged
        run: |
          # 差分がないと git diff --exit-code は 0 を返す
          if git diff --exit-code origin/${{ github.base_ref }} -- composables/ReleaseNotes.ts >/dev/null ; then
            echo "::error file=composables/ReleaseNotes.ts::ReleaseNotes.ts is not changed.\nIs this intended action?"
            exit 1
          fi
  check-duplicated-release-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile --ignore-scripts

      - run: pnpm exec nuxt prepare

      - run: pnpm exec tsx ci/duplicateVersions.ts

  check-new-records:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch origin ${{ github.base_ref }} --depth=1

      - name: Warn if NewScoreRecords.ts is unchanged
        run: |
          # 差分がないと git diff --exit-code は 0 を返す
          if git diff --exit-code origin/${{ github.base_ref }} -- composables/NewScoreRecords.ts >/dev/null ; then
            echo "::error file=composables/NewScoreRecords.ts::NewScoreRecords.ts is not changed.\nIs this intended action?"
            exit 1
          fi

  check-generetable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile --ignore-scripts

      - run: pnpm exec nuxt prepare

      - run: pnpm exec nuxt generate